Repository da-nyee/git-branch-strategy-practice, pull requests merged in 2021-07, with the labels that each got.

#14 [다니] Step1 자기소개 추가
  README.md
  da-nyee.md
Labels: backend

#12 [크리스] Step1 자기소개 추가
  README.md
  chris.md
Labels: frontend

#13 [브콜] Step1 자기소개 추가
  README.md
  beuccol.md
Labels: frontend

#1 [케빈] Step1 자기소개 추가
  KEVIN.md
  README.md
Labels: backend

#7 [마크] Step1 자기소개 추가
  .idea/.gitignore
  .idea/git-branch-strategy-practice.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  README.md
  binghe819.md
Labels: backend

#8 [손너잘] Step1 자기소개 추가
  NEOZAL.md
  README.md
Labels: backend

#26 [케빈] Step2 핫픽스 대응 추가
  README.md
Labels: bug

#24 [크리스] Step2 역할 추가
  README.md
  chris.md
Labels: frontend

#28 [브콜] Step2 역할추가
  README.md
Labels: frontend

#30 [다니] Step2 역할 추가
  README.md
Labels: backend

#32 [코다] 2단계 추가
  README.md
Labels: backend

#33 [손너잘] Step2 역할 추가
  README.md
Labels: backend

#34 feat: 버전 0.2
  README.md
  chris.md
Labels: release

#45 feat: 다니 제 2 역할 추가
  README.md
Labels: backend

#44 [크리스] 두번째 역할 추가
  README.md
Labels: frontend

#43 [코다] 두번째 역할 추가
  README.md
Labels: backend

#42 [마크] Step3 제 2 역할 추가
  README.md
Labels: backend

#48 [다니] Step3 담당 코치 추가
  README.md
Labels: bug

#52 Step3 끝
  README.md
Labels: release
